# Generated by Django 4.0.4 on 2022-05-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_ip', models.CharField(help_text='IP Address of the question asker', max_length=40)),
                ('q_title', models.CharField(help_text='Question Title', max_length=200)),
                ('q_content', models.TextField(help_text='Question Content', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_content', models.TextField(help_text='Question Content', max_length=500)),
                ('a_question', models.ForeignKey(help_text='Which question this answer is answering', on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
    ]
